### ISSUE TITLE
Are Webviews supported?

### ISSUE THREAD

**Issue by lopesc** [redhat-developer/vscode-extension-tester#1]
Are Webviews supported or is there plans to support them in the future?

**Comment by jrichter1** [comment]
Welcome, and thanks for the issue.

As of now, there is no explicit support for webviews, as I'm not quite sure what to do with them.

Locating one is the same as locating an open editor, which EditorsView already does. But the content is always wrapped in a frame. The best I can do here is to try switching webdriver to the particular frame when accessing the view. Navigating the content would then be the user's job, since it is arbitrary HTML inside.

Is that what you'd be looking for?

**Comment by lopesc** [comment]
> The best I can do here is to try switching webdriver to the particular frame when accessing the view. > Navigating the content would then be the user's job, since it is arbitrary HTML inside.


Yes, I suppose something like that would be quite sensible. At a minimum, I would hope to have a Webview container page object, which would abstract the detection of the iframe within the Editor. After that, as you say, the user can take it from there.

**Comment by jrichter1** [comment]
Sorry for the late response, got a bit sidetracked.

Anyway, I've tried the suggested approach. Sadly, even thought I am able to switch webdriver into the containing iframe, I just can't access (or even see) any inner HTML. At this point I'm struggling for ideas, as I feel like I've tried all the tricks I could get my hands on, with no luck. 

Unless something miraculously pops up, I feel like webview support is not meant to be. But if you stumble upon a solution, suggestions an PRs are always welcome.

**Comment by lakxraju** [comment]
Hi @jrichter1 , do you have any updates on webView support?

**Comment by jrichter1** [comment]
@lakxraju sadly, nothing so far. I can't figure out how to access the inner HTML of a webview.

**Comment by txava** [comment]
I was able to get access the HTML of a webview but you need to set the **windowTypes** with  "webview" in the ChromeDriver in order to be able to get a handle to the webviews.
I've already submitted a PR to support this option here: https://github.com/SeleniumHQ/selenium/pull/7897

You can get an idea of what i'm talking about by looking at the following snippet (needs refactoring, yes :)):
```
export async function findViewsByLocator(locator: Locator): Promise<string[]> {
  const { driver } = VSBrowser.instance;
  const handles = await driver.getAllWindowHandles();
  const tasks = handles.map(handle => {
    return async (): Promise<string | null> => {
      await driver.switchTo().window(handle);
      const title = await driver.getTitle();
      if (title.includes('Virtual Document')) {
        await driver.switchTo().frame(0);
        const elements = await driver.findElements(locator);

        if (elements.length > 0) {
          return handle;
        }
        return null;
      }
      return null;
    };
  });

  const results = await pSeries(tasks);
  return results.filter(result => result !== null) as string[];
}
```

**Comment by jrichter1** [comment]
@txava I have no idea how you found that out, but it's awesome nonetheless :)

**Comment by jrichter1** [comment]
[Webviews](https://github.com/redhat-developer/vscode-extension-tester/wiki/WebView) are now in 2.4.0, closing this. If you have some problems with them, feel free to open a new issue,

**Comment by lopesc** [comment]
Thanks @jrichter1 !
