### ISSUE TITLE
[🚀 Request] Allow to generate extension test coverage using c8 plugin

### ISSUE THREAD

**Issue by djelinek** [redhat-developer/vscode-extension-tester#1160]
### Describe the request

generate test coverage reports for extension tested by ExTester

https://www.npmjs.com/package/c8

### Usage

https://github.com/redhat-developer/vscode-extension-tester/commit/e38708bd57f01d4541b7bbfd502c7835563734ed

**Comment by TamiTakamiya** [comment]
@djelinek Thanks for the updates. I started looking at this again with the latest code base.

**Comment by TamiTakamiya** [comment]
I was thinking of using nyc instead of c8 simply because we have been using nyc in [our project](https://github.com/ansible/vscode-ansible). However, I got to know that Microsoft's [vscode-test-cli](https://github.com/microsoft/vscode-test-cli/tree/main) now supports [code coverage through c8](https://github.com/microsoft/vscode-test-cli/pull/20) and it is supporting the `--coverage` flag that @djelinek  suggested above. I will take a look at their code and consider how ExTester code can be modified to support the flag.

**Comment by TamiTakamiya** [comment]
Draft PR #1227 was created. I will add some more refinements and send it for review. Thanks.
