### ISSUE TITLE
Close "Do you want to save your workspace configuration?" dialog

### ISSUE THREAD

**Issue by chakraborty-slx** [redhat-developer/vscode-extension-tester#148]
I am try to write a test case which changes the workspace configuration and then creates a new project using vscode command with a directory path.

Now i am getting this dialog prompt , I am not sure how can i close this dialog using the tester API?
![Screenshot from 2020-08-01 11-08-56](https://user-images.githubusercontent.com/26390759/89102010-7f118100-d405-11ea-8a12-3f3dff3a9c77.png)

**Comment by jrichter1** [comment]
Currently there is no API to handle dialogs like this. And since it's a native dialog, there is no pretty way to do it either. I guess it could be done with key presses like the [open dialog](https://github.com/redhat-developer/vscode-extension-tester/wiki/OpenDialog). Maybe you could actually use `OpenDialog` to confirm it for now.

**Comment by chakraborty-slx** [comment]
@jrichter1 thanks for the reply, I tried but it didn't capture the save button, I have changed my test case for now. I will close this ticket.
