### ISSUE TITLE
How to pass mocha options like grep to vscode-extension-tester

### ISSUE THREAD

**Issue by ajcrypto** [redhat-developer/vscode-extension-tester#179]
I have multiple test cases(describe stat.) in my file. I want to run a single describe. With mocha we can do that with 'mocha --grep <matching-pattern>' .

My package.json looks like

"scripts": {
		"vscode:prepublish": "npm run compile",
		"compile": "tsc -p ./",
		"lint": "eslint . --ext .ts,.tsx",
		"watch": "tsc -watch -p ./",
		"ui-test": "MOCHAWESOME_REPORTFILENAME=AutomationReport MOCHAWESOME_REPORTTITLE=MyReport  extest setup-and-run  out/ui-test/*.js "
	},

**Comment by jrichter1** [comment]
You can create a mocha configuration file. By convention, if you name it `.mocharc.js` (or `.json`, `.yml`) and put it into the root of your project, it will be picked up automatically. Otherwise use the `-m <path/to/config/file>` option in your command line.

As far as the format goes, you can check out the examples here:
https://github.com/mochajs/mocha/blob/master/example/config/

In your case it could look as simple as:
```javascript
module.exports = {
    grep: 'pattern'
}
```

More info here:
https://github.com/redhat-developer/vscode-extension-tester/wiki/Mocha-Configuration

**Comment by ajcrypto** [comment]
ahh Thanks worked for me 👍
