### ISSUE TITLE
Create one example for each VSCode API

### ISSUE THREAD

**Issue by AllanOricil** [redhat-developer/vscode-extension-tester#306]
Sorry, but it is kind hard to understand how to use your lib without having more test examples. Could you create one for each? Like, I was able to setup the cli on my project and run it to download vscode version and a chrome webdriver (which was not the chrome driver for my google chrome). Then I run the simple test example and it ran successfully but nothing appeared and no error was thrown.

**Comment by jrichter1** [comment]
The project's wiki contains most info on the available API, both for test setup and actual test code.

Particularly [this page](https://github.com/redhat-developer/vscode-extension-tester/wiki/Page-Object-APIs) shows what you can do with the page objects. These are mostly commented code snippets that show how to use the page objects. They are not, however, full test case examples with setup.

If you want to see some real test cases including all the available API, feel free to rummage around the framework's [tests](https://github.com/redhat-developer/vscode-extension-tester/tree/master/test/test-project).

Is that what you were looking for? If not, please specify, because `one example for each VSCode API` is a bit vague.

**Comment by AllanOricil** [comment]
Well, it was kind hard to get started using the framework using the wiki. For instance, the TerminalView example is not really a full working example. It would be nice to have the test project using every API you have on the framework. Then we can execute the example project on our computers and attach the debugger to understand it.

**Comment by AllanOricil** [comment]
To summarize, improve the `sample-project` with an example that uses everything

**Comment by jrichter1** [comment]
sample-project now has a sample test cases for most of the API
