### ISSUE TITLE
Unable to install extension-tester in docker on M1 Mac due to nut-tree

### ISSUE THREAD

**Issue by Foxhoundn** [redhat-developer/vscode-extension-tester#315]
When trying to `npm install --save-dev vscode-extension-tester@latest`

the following error is thrown

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @nut-tree/nut-js@1.5.0: wanted {"os":"linux,darwin,win32","arch":"x64,ia32"} (current: {"os":"linux","arch":"arm64"})
npm ERR! notsup Valid OS:    linux,darwin,win32
npm ERR! notsup Valid Arch:  x64,ia32
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: arm64
```

The docker image used is `node`

Any workaround for this?

Thanks

**Comment by jrichter1** [comment]
This seems to be caused by the -native package. I'd recommend not using the native package any more,  since there are now ways to handle dialogs inside the browser.

**Comment by djelinek** [comment]
no more 'nut-tree' dependency

**Comment by djelinek** [comment]
Hi @mikhail-g 

- "-native" package was deprecated while ago, it was separate package which should had handle interaction with native OS objects (context menus, modal dialogs, ...), because of huge instabillity and big maintain requirements it was dropped and we are requiring to not use native

- instead of native ones, you can handle modal dialogs another way - see 
our Wiki page for details - https://github.com/redhat-developer/vscode-extension-tester/wiki#using-dialogs
