### ISSUE TITLE
Sidevar view item is not opened and showing error.

### ISSUE THREAD

**Issue by afrinj** [redhat-developer/vscode-extension-tester#325]
Hello,

Want to click on the side bar view icon and want to open it. 
Using the source from here : https://github.com/redhat-developer/vscode-extension-tester/blob/master/test/test-project/src/test/xsideBar/sideBarView-test.ts

    `
    describe('SideBarView', () => {
    let view: SideBarView;

    before(async () => {
        view = await (await new ActivityBar().getViewControl('Explorer')).openView();
    });
    ` 

This above code shows error : 

`    Object is possibly 'undefined'.ts(2532) `

What is your suggestion or fix to use this properly??

**Comment by jrichter1** [comment]
This is most likely due to your project having strict type checks enabled (which is completely fine, the test project doesn't have it for convenience). It all comes to `getViewControl` returning `Promise<ViewControl | undefined>`, which in strict mode is handled as two separate types. In this case the compiler requires explicit information on what to do when the object is undefined.

Couple possible solutions:
 - cast the incriminated object to whatever defined type you need (essentially skipping the strict type check)
 `view = await (await new ActivityBar().getViewControl('Explorer') as ViewControl).openView();`
  
 - use a conditional statement to check if the object is defined (might need additional changes somewhere else in the code)
```typescript 
    const viewControl = await new ActivittyBar().getViewControl('Explorer');
    if (viewControl) {
        view = await viewControl.openView();
    }
```

 - use optional chaining
   -  declare `let view: SideBarView | undefined`
   - `view = await (await new ActivityBar().getViewControl('Explorer'))?.openView();`
   - any time you call `view` methods, use optional `await view?.getTitlePart()`

**Comment by afrinj** [comment]
@jrichter1  thanks for the reply. But i am bit surprised as even `await new ActivittyBar().getViewControl('Explorer');` returns undefined object.

**Comment by afrinj** [comment]
![Uploading image.png…]()

**Comment by afrinj** [comment]
![image](https://user-images.githubusercontent.com/87761516/126503707-1575b136-b7d7-45fc-b27b-1e51a34d3e11.png)

**Comment by jrichter1** [comment]
Nope, not happening here with the latest version. What combination of the library version and vscode version is this happening with?

**Comment by afrinj** [comment]
@jrichter1  wow... thanks. Updating my vscode extension test to `4.1.1` fixed this. Previously it was `4.0.3`
