### ISSUE TITLE
Select folder from pop up window for path setup.

### ISSUE THREAD

**Issue by noorshiblee** [redhat-developer/vscode-extension-tester#327]
Hello there,

Thanks for this really good  package designed to help  to run UI tests. I have started to use it recently but one point i need ask for help.

Problem:
I have to set some path by selecting folder from a popup window. And i was trying to do this by  vscode-extension-tester.
**Is there any way or suggestion that you can give me to select any folder from pop up view to continue my task?**

**Comment by jrichter1** [comment]
I assume by pop up window you mean the one that pops up when you select File > Open Folder for example. Now that one is a pain to use because it is a native dialog outside the browser.

The preferred way is to use vscode settings that turn these pop ups into simple input boxes. You would then just fill in the path into the input box and confirm.

Info on the settings is on the [wiki](https://github.com/redhat-developer/vscode-extension-tester/wiki#opening-files-and-folders).

**Comment by noorshiblee** [comment]
Great ... thanks for the update.
