### ISSUE TITLE
Is it possible to get coverage reports while running the tests on vscode extension

### ISSUE THREAD

**Issue by adityaaswani** [redhat-developer/vscode-extension-tester#372]
We are able to setup the vscode extension tester for our extension and run few auto mocha TCs.
Is it possible to get coverage reports while running the tests on vscode extension

**Comment by ssbarnea** [comment]
First observation was that `nyc -a extest ...` failed to run while removing the `-a` allowed it to run, but it measured only the coverage of test files themselves and some node modules, but none of the files I was hoping to see a coverage for like my `src/extension.ts` file.

I doubt this would work without adding some special code when calling vscode itself as the extension would be run by a different process.

**Comment by djelinek** [comment]
Closing - no issue activity for a long time. Feel free to reopen if needed.

**Comment by TamiTakamiya** [comment]
Update: I could figure out how to enable code coverage and opened [a PR on the vscode-ansible repo](https://github.com/ansible/vscode-ansible/pull/1053). It was actually an issue in our test code, pls look at the PR for details.

![Screenshot from 2024-01-20 09-19-58](https://github.com/redhat-developer/vscode-extension-tester/assets/27698807/f28ef0fa-fb7e-45f7-b53b-326232aff4fb)

**Comment by TamiTakamiya** [comment]
I have just deleted two comments I posted here because they were actually out of topics. I was trying to get code coverage report for our e2e tests, which were not using vscode-extension-tester.

However, it might be somehow related to a possibe solution to get code coverage on the UI test with vscode-extension-tester.  Our e2e test is using a runner, which is similar to the one descrined in [this vscode documentation page](https://code.visualstudio.com/api/working-with-extensions/testing-extension). I was trying to get code coverage by applying the technique shown in [this page ](https://frenya.net/blog/vscode-extension-code-coverage-nyc). The attempt was not successful initially, but **it started working after I stopped loading the code from a .vsix file**

I checked the [CHANGELOG](https://github.com/redhat-developer/vscode-extension-tester/blob/main/CHANGELOG.md) and found that vscode-extension-tester 2.1.0 removed the --extensionDevelopmentPath flag, which specifies the location from which the target extension is stored as source codes.  Even though [the wiki page](https://github.com/redhat-developer/vscode-extension-tester/wiki/Test-Setup#build-and-install-extension-from-vsix) still states 

```
Build and Install Extension from vsix
To manually build and install your extension. This step is not necessary to run the tests, 
since the framework will run the extension directly from source.
```

I assume currently all UI tests using vscode-extension-tester loads the test target extension from .vsix file after  the -extensionDevelopmentPath flag support was dropped. Then I just wonder **we may be able to get code coverage from UI tests using vscode-extension-tester if we re-enable the --extensionDevelopmentPath flag.**

From the issue #430, I noticed there was [a fork that re-enabled the --extensionDevelopmentPath flag](https://github.com/timvahlbrock/vscode-extension-tester).  I would like to try it out to see if it can be used for generating the code coverage report.

**Comment by TamiTakamiya** [comment]
I re-enabled the --extensionDevelopmentPath flag. It was straightforward thanks to the fork mentioned my comment above.  The result is[ this commit of my fork](https://github.com/redhat-developer/vscode-extension-tester/compare/main...TamiTakamiya:vscode-extension-tester:reenable-extensionDevelopmentPath-flag).

Then I tried to get code coverage. So far I could not get valid code coverage with nyc, but another tool c8 seemed to work magically.  Following the command I used:
```
extest get-vscode -c max -s out/test-resources && extest get-chromedriver -c max -s out/test-resources && extest install-from-marketplace redhat.vscode-yaml ms-python.python -e out/ext -s out/test-resources && c8 extest run-tests -d . -s out/test-resources -e out/ext --code_settings test/testFixtures/settings.json out/client/test/ui-test/allTestsSuite.js
```
`c8` is placed in front of `extest run-tests` and `-d .` is for specifying a `extensionDevelopmentPath`.

Though we still have to examine closely the coverage report generate by `c8`, but at the first glance, it looks reasonable.
![Screenshot from 2024-02-09 01-21-15](https://github.com/redhat-developer/vscode-extension-tester/assets/27698807/f6b423de-c4b7-48fd-97ea-ac87ad3b00cf)

**Comment by djelinek** [comment]
Hello @TamiTakamiya , that looks really nice and promising 👍🏻

**Comment by TamiTakamiya** [comment]
[Enabled code coverage on the test-project of extenstion tester](https://github.com/redhat-developer/vscode-extension-tester/commit/e38708bd57f01d4541b7bbfd502c7835563734ed). It can be executed with `npm run coverage` and the report is generated in `test/test-project/coverage`.  Naturally it shows far better code coverage than ours :smile: 

![Screenshot from 2024-02-10 01-30-30](https://github.com/redhat-developer/vscode-extension-tester/assets/27698807/aab79c6c-d0d9-40f0-9f8e-5213e5affb99)

**Comment by Achal1607** [comment]
It is super cool. So is it possible to integrate this piece of code in the master branch, so that people can directly use this feature by installing the library? 
@djelinek Can you please again introduce --extension_development_path flag so that people can also obtain code-coverage of the UI tests written using approach given by @TamiTakamiya ?

**Comment by djelinek** [comment]
> It is super cool. So is it possible to integrate this piece of code in the master branch, so that people can directly use this feature by installing the library? @djelinek Can you please again introduce --extension_development_path flag so that people can also obtain code-coverage of the UI tests written using approach given by @TamiTakamiya ?

Hello, let me check why was that flag removed in past and after that we can figure out how to provide this nice possibility of test coverage to the dependant extensions 🙂 

from now it will be tracked here https://github.com/redhat-developer/vscode-extension-tester/issues/1160

@TamiTakamiya if you would like to you can continue on that issue, it will be very welcomed, you did a lot of work on it already 🙂
