### ISSUE TITLE
Debug on tests failing and or screenshots

### ISSUE THREAD

**Issue by brianignacio5** [redhat-developer/vscode-extension-tester#390]
Using version `v4.2.3`, I have some tests running on GitHub Actions but no screenshot is being taken. I was wondering if there something I'm not configuring or if there is a way to find some information about what went wrong.

Locally tests works well and runs ok/

**Comment by jrichter1** [comment]
I've checked and screenshot capture seems to be working, note it will not trigger when an error occurs in a hook (like `before`), only when a test case fails.

Anyway, potential screenshots would be in your `test-resources/screenshots` folder by default. Make sure to upload them in your workflow to access them.

something like https://github.com/redhat-developer/vscode-extension-tester/blob/master/.github/workflows/linux.yml#L40 (just make sure to point to the appropriate folder, since I'm using a custom one)

**Comment by brianignacio5** [comment]
Thanks for the reply, I'll try this.
