### ISSUE TITLE
Executing helloworld-sample test always FAIL due to time-out at "Launching browser..." step

### ISSUE THREAD

**Issue by slbSTM** [redhat-developer/vscode-extension-tester#400]
Hi,

Even with the latest PRs that fixes the issues reported as #395, I still cannot execute the helloworld-sample test on my Linux installations (tested with both RHEL7 and Ubuntu 20, and requiring http_proxy). The test execution always FAIL due to time-out at the "Launching browser..." step (located in browser.js / start() method). And so whatever the target version of VS Code specified in the package.json.

Reverting back to previous versions of vscode-extension-tester in package.json of the helloworld-sample test shows that this issue appeared only with the latest versions:
- up to vscode-extension-tester 4.2.1: no problem, helloworld-sample test runs well
- from vscode-extension-tester 4.2.2: helloworld-sample test stays stuck at "Launching browser..." step

Could you please helpto solve this issue ?

**Comment by sleblanc38** [comment]
Sounds like a proxy issue again since I manage to workaround it by following these steps:

1. Before calling "npm run ui-test", execute the following command:
$ export GLOBAL_AGENT_HTTP_PROXY=$http_proxy
Without this action, "npm run ui-setup" fails with the following error (see issue #395):
RequestError: getaddrinfo ENOTFOUND update.code.visualstudio.com

2. Execute the "extest" command with the "--offline" option.

3. Execute the following command before running the UI test:
$ unset GLOBAL_AGENT_HTTP_PROXY

Note that all these steps are necessary to not staying stuck at the "Launching browser..." stage.

**Comment by SURYASPR** [comment]
Hi @sleblanc38 

Is helloworld-sample test working for you now? It's launching the new instance for me but its failing as mentioned in this issue
https://github.com/redhat-developer/vscode-extension-tester/issues/410

Are you also using the same versions which I've used ?

**Comment by sleblanc38** [comment]
Hi @SURYASPR ,

Yes the example works for me, but only with the workaround explained in my 2nd comment.

I tested with the following SW components:
VS Code: 1.63.2 for Linux x64
Node.js: 16.13.0 for Linux x64
OS: Linux RHEL7 x64
