### ISSUE TITLE
Error: Channel xxx not found only happened on Macos

### ISSUE THREAD

**Issue by SLdragon** [redhat-developer/vscode-extension-tester#409]
I am using this api to select output channel, it works fine on Windows and Linux, but failed on Macos:

```ts
  const output = await new BottomBarPanel().openOutputView();
  await output.selectChannel("xxx");
```

it will throw error "Error: Channel xxx not found"

**Comment by SURYASPR** [comment]
What is the vscode version and vscode-extension-tester version you are using?

**Comment by odockal** [comment]
Is this issue still actual? Is it something we should take a look or did you manage to find a solution? Thanks.

**Comment by kiwi-bui** [comment]
I am encountering this, latest version of everything.

**Comment by ajdor** [comment]
This is an issue on MacOS only since VSCode on MacOS uses native context menus which are not WebElements and cannot be seen by vscode-extension-tester.
AFAIK, there isn't a way to use regular context menu like those on Linux or Windows.
See https://github.com/microsoft/vscode/blob/f7e12a3a928aa69fc1991a00298ff62291207864/src/vs/workbench/services/contextmenu/electron-sandbox/contextmenuService.ts#L49

**Comment by djelinek** [comment]
Closing - no issue activity for a long time. Feel free to reopen if needed.
