### ISSUE TITLE
Input.getText() returns an empty string

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-extension-tester#42]
To reproduce the issue:

1. check out this branch https://github.com/xorye/vscode-extension-tester/tree/get-text
2. navigate to vscode-extension-tester/sample-projects/helloworld-sample.
    I have changed this sample extension to activate on startup and display an input box with `vscode.window.showInputBox`
3. run `npm run ui-test`
4. [This test](https://github.com/xorye/vscode-extension-tester/blob/ba0265aa35c81f571cc0bda014abaff9975058ae/sample-projects/helloworld-sample/src/ui-test/hello-world-test.ts#L17-L22) fails because `text = ''`

**Comment by xorye** [comment]
Also a side question, if I call `await new InputBox().wait();` and there is no Input Box currently created/visible, will this call wait until an Input Box is created/visible and then resolve?

Because if I comment out `vscode.window.showInputBox({value: 'hello'});` from `extensions.ts` and call `await new InputBox().wait();`, I get the following error which for some reason I cannot catch with a `try` and `catch`:
```
Uncaught NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".quick-input-widget"}
  (Session info: chrome=76.0.3809.146)
  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Linux 5.0.17-300.fc30.x86_64 x86_64)
```

**Comment by jrichter1** [comment]
Okay... didn't notice the lack of tests for this one. For some reason the text just disappeared from the DOM. Neither `text`, nor `value` contain anything meaningful any more :(

As far as the side question goes, it's a bit complicated. When you call the constructor, webdriver schedules the lookup for the given DOM element. The `wait` method then waits for the element to become visible. For some reason in vscode, until something opens an input box for the first time, the DOM element is not only hidden, but doesn't exist at all. That's why you're getting a lookup error.

The inability to catch the error comes with the way the lookup is hooked into webdriver. Essentially the problem is an async call has to be done from the constructor, which in itself can only be synchronous. So the async call is just floating in the void until another task picks up on it and synchronizes the chain (like calling `wait` on a new element). If something goes wrong before the chaining happens, there is no way to access the error. I've yet to find a way to work around this.

Hopefully it makes some sense, sorry for the wall of text. I'm going to fix `getText` now.

**Comment by xorye** [comment]
I see. Thank you so much for your explanation and help @jrichter1 !

> For some reason in vscode, until something opens an input box for the first time, the DOM element is not only hidden, but doesn't exist at all. That's why you're getting a lookup error.

As a workaround, I was thinking I could quickly call a command/open an input box (and then close it right away) before all my tests so that the element exists and is hidden (I think?). I haven't tried this yet, but what do you think about this idea?

**Comment by jrichter1** [comment]
> As a workaround, I was thinking I could quickly call a command/open an input box (and then close it right away) before all my tests so that the element exists and is hidden (I think?). I haven't tried this yet, but what do you think about this idea?

This could work, but you need to be aware that input box and command prompt are two different elements. You'd need to open both if you want to use them this way.

What I used to do is put an actual wait for the DOM element to appear before trying to construct either page object.
```typescript
await driver.wait(until.elementLocated(By.className('quick-input-widget')))
```
But I just realized I could simply add some static factory methods to these page objects that would do just the thing.
