### ISSUE TITLE
[Request] Expose Wiki files to "docs" folder 

### ISSUE THREAD

**Issue by mlorinc** [redhat-developer/vscode-extension-tester#887]
Only maintainers can see and edit wiki files. So, people outside of Red Hat cannot contribute to wiki at all, which I find unfortunate.

**Comment by EcksDy** [comment]
I see that a lot of the wiki pages are outdated, and wanted to fix some of them as I go along exploring the package.

Is there interest in opening up the wiki to the masses?
Researching on approaches to community docs I've stumbled upon [this answer on SO](https://stackoverflow.com/a/58692638/3204453).

I'd be willing to work something along these lines in this repo, using github actions and a `wiki/` directory.

**Comment by djelinek** [comment]
Hello @EcksDy thank you for your interest in this area 🙂 . I would be more than happy if anyone would update documentation and also there is no reason to not expose documentation currently placed at GH Wiki to all contributors.

Did you considered also for example simple usage of GH Pages instead another service?

**Comment by EcksDy** [comment]
@djelinek 
My thoughts were to keep things as close to current state as possible, meaning I intended to leave the wiki in the GH Wiki tab.

- Make a `wiki/` dir inside the repo with all wiki markdowns in it
- Add a job to `main.yml` workflow called `update-wiki` that will:
  - Checkout current repo
  - Copy files in `wiki/` dir
  - Checkout wiki repo
  - Commit all files in `wiki`
  - Push to the wiki repo
  
The job would run only on push to main, since only privileged users can merge to main they should also have access to the wiki repo, so the GH action should hopefully have access too.

I'm not very familiar with how GH pages operate. If you have ideas that can simplify or improve the above plan, let me know and I'll start working in the direction.
